services:
  adminer:
    container_name: tutlayt_adminer
    image: adminer
    environment:
      - ADMINER_SERVERS=${ADMINER_SERVERS}
    ports:
      - 8080:8080
    volumes:
      - ./adminer-plugin.php:/var/www/html/plugins-enabled/login-servers.php

  database:
    container_name: tutlayt_databse
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432

  # flyway:
  #   depends_on:
  #     - database
  #   container_name: tutlayt_flyway
  #   image: flyway/flyway
  #   entrypoint: ['sh']
  #   command: -c "/wait-for-it.sh database:5432 -- flyway -url=jdbc:postgresql://database:5432/${POSTGRES_DB} -user=${POSTGRES_USER} -password=${POSTGRES_PASSWORD} migrate"
  #   volumes:
  #     - ./database/scripts:/flyway/sql
  #     - ./database/wait-for-it.sh:/wait-for-it.sh
