type Author {
  id: ID!
  name: String!
  books: [Book]
}

type Book {
  id: ID!
  title: String!
  author: Author!
}

type Query {
  author(id: ID!): Author
  book(id: ID!): Book!
  name(id: ID!): String
}

type Mutation {
  addAuthor(name: String!): Author!
}

type Subscription {
  authorAdded: Author
}
