targets:
  $default:
    builders:
      graphql_generator:
        enabled: true

builders:
  graphql_generator:
    import: "package:graphql_generator/graphql_generator.dart"
    builder_factories: ["graphqlGenerator"]
    build_extensions: {".dart": [".graphql.dart"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
    


