name: graphql_generator
description: A graphql query generator.
publish_to: 'none'
version: 0.0.1
environment:
  sdk: '>=3.0.0-257.0.dev <4.0.0'
dependencies:
  build: ^2.3.1
  source_gen: ^1.2.7
  graphql_decorator:
    path: ../graphql_decorator
