name: tutlayt
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  faker: ^2.1.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  get: ^4.6.6
  graphql_flutter: ^5.1.1
  intl: ^0.18.0
  jwt_decoder: ^2.0.1
  logging: ^1.2.0
  path: ^1.8.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  ql_gen:
    path: ../ql_gen

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    - assets/images/not-found.png
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
