name: ql_gen
description: A starting point for Dart libraries or applications.
version: 0.0.1
repository: https://github.com/roadroot/tutlayt
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  args: ^2.4.0
  http: ^1.2.1
  tokenizer:
    path: ../tokenizer

dev_dependencies:
  lints: ^4.0.0
  test: ^1.21.0
