name: ql_gen
description: A starting point for Dart libraries or applications.
version: 0.0.1
repository: https://github.com/roadroot/tutlayt

environment:
  sdk: '>=3.0.0-218.1.beta <4.0.0'

dependencies: 
  args: ^2.4.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
